upstream speakspace_backend {
    least_conn;
    server backend:4000;
    server backend:4000;
    keepalive 32;
}

server {
    listen 80;
    server_name 3.88.239.189.nip.io;

    # Certbot challenge path (MUST be available on Port 80)
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # API
    location /api/ {
        proxy_pass http://speakspace_backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # WebSockets
    location /socket.io/ {
        proxy_pass http://speakspace_backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Frontend
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}
